spring:
    application:
        name: RedditBE
    datasource:
        password: Ciao.ciao1
        url: jdbc:mysql://localhost:3306/redditdb
        username: root
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
server:
    port: 8081